# Site settings
title: Ryan's Blog
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog about projects I'm working on, development insights, and tech adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.gamnation.net" # the base hostname & protocol for your site
domain: blog.gamnation.net

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Leap-day theme settings
show_downloads: false # Don't show GitHub download links
# google_analytics: YOUR_GA_ID  # Uncomment and add your GA ID if you want analytics
